"""reach snapshots and diffs

Revision ID: 5fd8850d1593
Revises: 4552a499c0af
Create Date: 2026-08-26 16:05:11.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5fd8850d1593"
down_revision: str | None = "4552a499c0af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reach_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column(
            "taken_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "label", name="uq_snapshot_label"),
    )
    op.create_table(
        "reach_snapshot_edges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("principal_external_id", sa.Text(), nullable=False),
        sa.Column("principal_app_id", sa.Text(), nullable=False),
        sa.Column("resource_path", sa.Text(), nullable=False),
        sa.Column("resource_app_id", sa.Text(), nullable=False),
        sa.Column("sensitivity", sa.Integer(), nullable=False),
        sa.Column(
            "capability",
            sa.Enum(
                "read",
                "write",
                "admin",
                "delete",
                "impersonate",
                name="capability",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["reach_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id",
            "principal_external_id",
            "resource_path",
            "capability",
            name="uq_snapshot_edge",
        ),
    )
    op.create_index(
        "ix_snapshot_edges_snapshot", "reach_snapshot_edges", ["snapshot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshot_edges_snapshot", table_name="reach_snapshot_edges")
    op.drop_table("reach_snapshot_edges")
    op.drop_table("reach_snapshots")
    # ### end Alembic commands ###
