"""initial canonical schema

Revision ID: d83b1ba52717
Revises:
Create Date: 2026-08-18 14:19:53.407496
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d83b1ba52717"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("app_id", sa.Text(), nullable=False),
        sa.Column("stream", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "first_failed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("app_id", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("human", "service", "agent", "app", name="principal_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                "deactivated",
                "deleted",
                name="principal_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_active_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "app_id", "external_id", name="uq_principal_identity"),
    )
    op.create_index("ix_principals_tenant_kind", "principals", ["tenant_id", "kind"], unique=False)
    op.create_table(
        "resources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("app_id", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "repo",
                "sobject",
                "secret_path",
                "drive_file",
                "channel",
                "mailbox",
                name="resource_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sensitivity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "app_id", "external_id", name="uq_resource_identity"),
    )
    op.create_index("ix_resources_tenant_path", "resources", ["tenant_id", "path"], unique=False)
    op.create_table(
        "sync_watermarks",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("app_id", sa.Text(), nullable=False),
        sa.Column("stream", sa.Text(), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("last_success_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "app_id", "stream"),
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "oauth_token",
                "pat",
                "api_key",
                "vault_token",
                "session",
                "ssh_key",
                name="credential_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("issued_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "kind", "external_id", name="uq_credential_identity"),
    )
    op.create_index("ix_credentials_principal", "credentials", ["principal_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("app_id", sa.Text(), nullable=False),
        sa.Column("actor_principal_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_resource_id", sa.UUID(), nullable=True),
        sa.Column("ts", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("raw_ref", sa.Text(), nullable=False),
        sa.Column(
            "provenance",
            sa.Enum("api", "audit_log", "inferred", name="event_provenance", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_principal_id"], ["principals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_resource_id"], ["resources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "app_id", "raw_ref", name="uq_event_identity"),
    )
    op.create_index("ix_events_actor_ts", "events", ["actor_principal_id", "ts"], unique=False)
    op.create_index("ix_events_tenant_ts", "events", ["tenant_id", "ts"], unique=False)
    op.create_table(
        "identity_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("principal_a", sa.UUID(), nullable=False),
        sa.Column("principal_b", sa.UUID(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "external_id_exact",
                "email_exact",
                "sso_subject",
                "fuzzy_name",
                name="link_method",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "evidence_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["principal_a"], ["principals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["principal_b"], ["principals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("principal_a", "principal_b", "method", name="uq_link_identity"),
    )
    op.create_table(
        "reach_edges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column(
            "capability",
            sa.Enum(
                "read",
                "write",
                "admin",
                "delete",
                "impersonate",
                name="capability",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "path_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "principal_id", "resource_id", "capability", name="uq_reach_edge"
        ),
    )
    op.create_index("ix_reach_edges_resource", "reach_edges", ["resource_id"], unique=False)
    op.create_table(
        "grants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("resource_selector", sa.Text(), nullable=False),
        sa.Column("scope_raw", sa.Text(), nullable=False),
        sa.Column("capabilities", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("granted_by_principal_id", sa.UUID(), nullable=True),
        sa.Column("granted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source_app_id", sa.Text(), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["credential_id"], ["credentials.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["granted_by_principal_id"], ["principals.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "dedupe_key", name="uq_grant_dedupe"),
    )
    op.create_index("ix_grants_principal", "grants", ["principal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_grants_principal", table_name="grants")
    op.drop_table("grants")
    op.drop_index("ix_reach_edges_resource", table_name="reach_edges")
    op.drop_table("reach_edges")
    op.drop_table("identity_links")
    op.drop_index("ix_events_tenant_ts", table_name="events")
    op.drop_index("ix_events_actor_ts", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_credentials_principal", table_name="credentials")
    op.drop_table("credentials")
    op.drop_table("sync_watermarks")
    op.drop_index("ix_resources_tenant_path", table_name="resources")
    op.drop_table("resources")
    op.drop_index("ix_principals_tenant_kind", table_name="principals")
    op.drop_table("principals")
    op.drop_table("dead_letters")
    # ### end Alembic commands ###
